services:
  - type: web
    name: servidor-ensintonia
    env: node
    buildCommand: cd backend/server && npm ci && npm run migrate
    startCommand: cd backend/server && npm start
    plan: free
    region: oregon
